
Insert into PUB_QUERY_CONDITION
   (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, GUIDELINE, ID, IF_ATTRREFUSED, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MULTICORPREF, IF_MUST, IF_NOTMDCONDITION, IF_ORDER, IF_SUBINCLUDED, IF_SUM, IF_SYSFUNCREFUSED, IF_USED, INSTRUMENTSQL, ISCONDITION, LIMITS, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, PRERESTRICT, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE, EXT1, EXT2, EXT3, EXT4, EXT5)
 Values
   ('会计年度', 5, 42, 1, NULL, 
    NULL, 'year_query', '年份', NULL, '1001ZZ10000000G2E60C', 
    'N', 'Y', 'N', 'Y', 'N', 
    'N', 'N', 'N', 'N', 'Y', 
    'N', 'N', 'N', 'Y', 'Y', 
    NULL, 'N', 9999, NULL, '=', 
    '等于@', 0, '@@@@', '1001ZZ100000005SX9S1', NULL, 
    NULL, 0, NULL, NULL, '2017-09-22 02:05:08', 
    'N', NULL, NULL, NULL, NULL, 
    NULL, NULL);
COMMIT;
